// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_gen.proto

#ifndef PROTOBUF_proto_5fgen_2eproto__INCLUDED
#define PROTOBUF_proto_5fgen_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_proto_5fgen_2eproto();
void protobuf_AssignDesc_proto_5fgen_2eproto();
void protobuf_ShutdownFile_proto_5fgen_2eproto();

class PB_IsDangerousFrame_0;
class PB_IsDangerousFrame_0Vector;
class PB_IsDangerousMatch;
class PB_IsDangerousMatchSet;

// ===================================================================

class PB_IsDangerousFrame_0 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PB_IsDangerousFrame_0) */ {
 public:
  PB_IsDangerousFrame_0();
  virtual ~PB_IsDangerousFrame_0();

  PB_IsDangerousFrame_0(const PB_IsDangerousFrame_0& from);

  inline PB_IsDangerousFrame_0& operator=(const PB_IsDangerousFrame_0& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_IsDangerousFrame_0& default_instance();

  void Swap(PB_IsDangerousFrame_0* other);

  // implements Message ----------------------------------------------

  inline PB_IsDangerousFrame_0* New() const { return New(NULL); }

  PB_IsDangerousFrame_0* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_IsDangerousFrame_0& from);
  void MergeFrom(const PB_IsDangerousFrame_0& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PB_IsDangerousFrame_0* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 _0 = 1;
  void clear__0();
  static const int k0FieldNumber = 1;
  ::google::protobuf::int32 _0() const;
  void set__0(::google::protobuf::int32 value);

  // optional int32 _1 = 2;
  void clear__1();
  static const int k1FieldNumber = 2;
  ::google::protobuf::int32 _1() const;
  void set__1(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PB_IsDangerousFrame_0)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 _0_;
  ::google::protobuf::int32 _1_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_5fgen_2eproto();
  friend void protobuf_AssignDesc_proto_5fgen_2eproto();
  friend void protobuf_ShutdownFile_proto_5fgen_2eproto();

  void InitAsDefaultInstance();
  static PB_IsDangerousFrame_0* default_instance_;
};
// -------------------------------------------------------------------

class PB_IsDangerousFrame_0Vector : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PB_IsDangerousFrame_0Vector) */ {
 public:
  PB_IsDangerousFrame_0Vector();
  virtual ~PB_IsDangerousFrame_0Vector();

  PB_IsDangerousFrame_0Vector(const PB_IsDangerousFrame_0Vector& from);

  inline PB_IsDangerousFrame_0Vector& operator=(const PB_IsDangerousFrame_0Vector& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_IsDangerousFrame_0Vector& default_instance();

  void Swap(PB_IsDangerousFrame_0Vector* other);

  // implements Message ----------------------------------------------

  inline PB_IsDangerousFrame_0Vector* New() const { return New(NULL); }

  PB_IsDangerousFrame_0Vector* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_IsDangerousFrame_0Vector& from);
  void MergeFrom(const PB_IsDangerousFrame_0Vector& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PB_IsDangerousFrame_0Vector* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .PB_IsDangerousFrame_0 frames = 1;
  int frames_size() const;
  void clear_frames();
  static const int kFramesFieldNumber = 1;
  const ::PB_IsDangerousFrame_0& frames(int index) const;
  ::PB_IsDangerousFrame_0* mutable_frames(int index);
  ::PB_IsDangerousFrame_0* add_frames();
  ::google::protobuf::RepeatedPtrField< ::PB_IsDangerousFrame_0 >*
      mutable_frames();
  const ::google::protobuf::RepeatedPtrField< ::PB_IsDangerousFrame_0 >&
      frames() const;

  // @@protoc_insertion_point(class_scope:PB_IsDangerousFrame_0Vector)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::PB_IsDangerousFrame_0 > frames_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_5fgen_2eproto();
  friend void protobuf_AssignDesc_proto_5fgen_2eproto();
  friend void protobuf_ShutdownFile_proto_5fgen_2eproto();

  void InitAsDefaultInstance();
  static PB_IsDangerousFrame_0Vector* default_instance_;
};
// -------------------------------------------------------------------

class PB_IsDangerousMatch : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PB_IsDangerousMatch) */ {
 public:
  PB_IsDangerousMatch();
  virtual ~PB_IsDangerousMatch();

  PB_IsDangerousMatch(const PB_IsDangerousMatch& from);

  inline PB_IsDangerousMatch& operator=(const PB_IsDangerousMatch& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_IsDangerousMatch& default_instance();

  void Swap(PB_IsDangerousMatch* other);

  // implements Message ----------------------------------------------

  inline PB_IsDangerousMatch* New() const { return New(NULL); }

  PB_IsDangerousMatch* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_IsDangerousMatch& from);
  void MergeFrom(const PB_IsDangerousMatch& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PB_IsDangerousMatch* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 rp = 1;
  void clear_rp();
  static const int kRpFieldNumber = 1;
  ::google::protobuf::int32 rp() const;
  void set_rp(::google::protobuf::int32 value);

  // optional int32 tr = 2;
  void clear_tr();
  static const int kTrFieldNumber = 2;
  ::google::protobuf::int32 tr() const;
  void set_tr(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PB_IsDangerousMatch)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 rp_;
  ::google::protobuf::int32 tr_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_5fgen_2eproto();
  friend void protobuf_AssignDesc_proto_5fgen_2eproto();
  friend void protobuf_ShutdownFile_proto_5fgen_2eproto();

  void InitAsDefaultInstance();
  static PB_IsDangerousMatch* default_instance_;
};
// -------------------------------------------------------------------

class PB_IsDangerousMatchSet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PB_IsDangerousMatchSet) */ {
 public:
  PB_IsDangerousMatchSet();
  virtual ~PB_IsDangerousMatchSet();

  PB_IsDangerousMatchSet(const PB_IsDangerousMatchSet& from);

  inline PB_IsDangerousMatchSet& operator=(const PB_IsDangerousMatchSet& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_IsDangerousMatchSet& default_instance();

  void Swap(PB_IsDangerousMatchSet* other);

  // implements Message ----------------------------------------------

  inline PB_IsDangerousMatchSet* New() const { return New(NULL); }

  PB_IsDangerousMatchSet* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_IsDangerousMatchSet& from);
  void MergeFrom(const PB_IsDangerousMatchSet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PB_IsDangerousMatchSet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .PB_IsDangerousMatch matches = 1;
  int matches_size() const;
  void clear_matches();
  static const int kMatchesFieldNumber = 1;
  const ::PB_IsDangerousMatch& matches(int index) const;
  ::PB_IsDangerousMatch* mutable_matches(int index);
  ::PB_IsDangerousMatch* add_matches();
  ::google::protobuf::RepeatedPtrField< ::PB_IsDangerousMatch >*
      mutable_matches();
  const ::google::protobuf::RepeatedPtrField< ::PB_IsDangerousMatch >&
      matches() const;

  // @@protoc_insertion_point(class_scope:PB_IsDangerousMatchSet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::PB_IsDangerousMatch > matches_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_5fgen_2eproto();
  friend void protobuf_AssignDesc_proto_5fgen_2eproto();
  friend void protobuf_ShutdownFile_proto_5fgen_2eproto();

  void InitAsDefaultInstance();
  static PB_IsDangerousMatchSet* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PB_IsDangerousFrame_0

// optional int32 _0 = 1;
inline void PB_IsDangerousFrame_0::clear__0() {
  _0_ = 0;
}
inline ::google::protobuf::int32 PB_IsDangerousFrame_0::_0() const {
  // @@protoc_insertion_point(field_get:PB_IsDangerousFrame_0._0)
  return _0_;
}
inline void PB_IsDangerousFrame_0::set__0(::google::protobuf::int32 value) {
  
  _0_ = value;
  // @@protoc_insertion_point(field_set:PB_IsDangerousFrame_0._0)
}

// optional int32 _1 = 2;
inline void PB_IsDangerousFrame_0::clear__1() {
  _1_ = 0;
}
inline ::google::protobuf::int32 PB_IsDangerousFrame_0::_1() const {
  // @@protoc_insertion_point(field_get:PB_IsDangerousFrame_0._1)
  return _1_;
}
inline void PB_IsDangerousFrame_0::set__1(::google::protobuf::int32 value) {
  
  _1_ = value;
  // @@protoc_insertion_point(field_set:PB_IsDangerousFrame_0._1)
}

// -------------------------------------------------------------------

// PB_IsDangerousFrame_0Vector

// repeated .PB_IsDangerousFrame_0 frames = 1;
inline int PB_IsDangerousFrame_0Vector::frames_size() const {
  return frames_.size();
}
inline void PB_IsDangerousFrame_0Vector::clear_frames() {
  frames_.Clear();
}
inline const ::PB_IsDangerousFrame_0& PB_IsDangerousFrame_0Vector::frames(int index) const {
  // @@protoc_insertion_point(field_get:PB_IsDangerousFrame_0Vector.frames)
  return frames_.Get(index);
}
inline ::PB_IsDangerousFrame_0* PB_IsDangerousFrame_0Vector::mutable_frames(int index) {
  // @@protoc_insertion_point(field_mutable:PB_IsDangerousFrame_0Vector.frames)
  return frames_.Mutable(index);
}
inline ::PB_IsDangerousFrame_0* PB_IsDangerousFrame_0Vector::add_frames() {
  // @@protoc_insertion_point(field_add:PB_IsDangerousFrame_0Vector.frames)
  return frames_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::PB_IsDangerousFrame_0 >*
PB_IsDangerousFrame_0Vector::mutable_frames() {
  // @@protoc_insertion_point(field_mutable_list:PB_IsDangerousFrame_0Vector.frames)
  return &frames_;
}
inline const ::google::protobuf::RepeatedPtrField< ::PB_IsDangerousFrame_0 >&
PB_IsDangerousFrame_0Vector::frames() const {
  // @@protoc_insertion_point(field_list:PB_IsDangerousFrame_0Vector.frames)
  return frames_;
}

// -------------------------------------------------------------------

// PB_IsDangerousMatch

// optional int32 rp = 1;
inline void PB_IsDangerousMatch::clear_rp() {
  rp_ = 0;
}
inline ::google::protobuf::int32 PB_IsDangerousMatch::rp() const {
  // @@protoc_insertion_point(field_get:PB_IsDangerousMatch.rp)
  return rp_;
}
inline void PB_IsDangerousMatch::set_rp(::google::protobuf::int32 value) {
  
  rp_ = value;
  // @@protoc_insertion_point(field_set:PB_IsDangerousMatch.rp)
}

// optional int32 tr = 2;
inline void PB_IsDangerousMatch::clear_tr() {
  tr_ = 0;
}
inline ::google::protobuf::int32 PB_IsDangerousMatch::tr() const {
  // @@protoc_insertion_point(field_get:PB_IsDangerousMatch.tr)
  return tr_;
}
inline void PB_IsDangerousMatch::set_tr(::google::protobuf::int32 value) {
  
  tr_ = value;
  // @@protoc_insertion_point(field_set:PB_IsDangerousMatch.tr)
}

// -------------------------------------------------------------------

// PB_IsDangerousMatchSet

// repeated .PB_IsDangerousMatch matches = 1;
inline int PB_IsDangerousMatchSet::matches_size() const {
  return matches_.size();
}
inline void PB_IsDangerousMatchSet::clear_matches() {
  matches_.Clear();
}
inline const ::PB_IsDangerousMatch& PB_IsDangerousMatchSet::matches(int index) const {
  // @@protoc_insertion_point(field_get:PB_IsDangerousMatchSet.matches)
  return matches_.Get(index);
}
inline ::PB_IsDangerousMatch* PB_IsDangerousMatchSet::mutable_matches(int index) {
  // @@protoc_insertion_point(field_mutable:PB_IsDangerousMatchSet.matches)
  return matches_.Mutable(index);
}
inline ::PB_IsDangerousMatch* PB_IsDangerousMatchSet::add_matches() {
  // @@protoc_insertion_point(field_add:PB_IsDangerousMatchSet.matches)
  return matches_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::PB_IsDangerousMatch >*
PB_IsDangerousMatchSet::mutable_matches() {
  // @@protoc_insertion_point(field_mutable_list:PB_IsDangerousMatchSet.matches)
  return &matches_;
}
inline const ::google::protobuf::RepeatedPtrField< ::PB_IsDangerousMatch >&
PB_IsDangerousMatchSet::matches() const {
  // @@protoc_insertion_point(field_list:PB_IsDangerousMatchSet.matches)
  return matches_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_5fgen_2eproto__INCLUDED
