// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_gen.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto_gen.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PB_QueryAFrame_0_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PB_QueryAFrame_0_reflection_ = NULL;
const ::google::protobuf::Descriptor* PB_QueryAMatch_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PB_QueryAMatch_reflection_ = NULL;
const ::google::protobuf::Descriptor* PB_QueryBFrame_0_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PB_QueryBFrame_0_reflection_ = NULL;
const ::google::protobuf::Descriptor* PB_QueryBMatch_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PB_QueryBMatch_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_proto_5fgen_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_proto_5fgen_2eproto() {
  protobuf_AddDesc_proto_5fgen_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "proto_gen.proto");
  GOOGLE_CHECK(file != NULL);
  PB_QueryAFrame_0_descriptor_ = file->message_type(0);
  static const int PB_QueryAFrame_0_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryAFrame_0, _0_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryAFrame_0, _1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryAFrame_0, _2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryAFrame_0, _3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryAFrame_0, _4_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryAFrame_0, _5_),
  };
  PB_QueryAFrame_0_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PB_QueryAFrame_0_descriptor_,
      PB_QueryAFrame_0::default_instance_,
      PB_QueryAFrame_0_offsets_,
      -1,
      -1,
      -1,
      sizeof(PB_QueryAFrame_0),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryAFrame_0, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryAFrame_0, _is_default_instance_));
  PB_QueryAMatch_descriptor_ = file->message_type(1);
  static const int PB_QueryAMatch_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryAMatch, h1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryAMatch, pw_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryAMatch, state_),
  };
  PB_QueryAMatch_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PB_QueryAMatch_descriptor_,
      PB_QueryAMatch::default_instance_,
      PB_QueryAMatch_offsets_,
      -1,
      -1,
      -1,
      sizeof(PB_QueryAMatch),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryAMatch, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryAMatch, _is_default_instance_));
  PB_QueryBFrame_0_descriptor_ = file->message_type(2);
  static const int PB_QueryBFrame_0_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryBFrame_0, _0_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryBFrame_0, _1_),
  };
  PB_QueryBFrame_0_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PB_QueryBFrame_0_descriptor_,
      PB_QueryBFrame_0::default_instance_,
      PB_QueryBFrame_0_offsets_,
      -1,
      -1,
      -1,
      sizeof(PB_QueryBFrame_0),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryBFrame_0, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryBFrame_0, _is_default_instance_));
  PB_QueryBMatch_descriptor_ = file->message_type(3);
  static const int PB_QueryBMatch_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryBMatch, a1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryBMatch, h1_),
  };
  PB_QueryBMatch_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PB_QueryBMatch_descriptor_,
      PB_QueryBMatch::default_instance_,
      PB_QueryBMatch_offsets_,
      -1,
      -1,
      -1,
      sizeof(PB_QueryBMatch),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryBMatch, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_QueryBMatch, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_proto_5fgen_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PB_QueryAFrame_0_descriptor_, &PB_QueryAFrame_0::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PB_QueryAMatch_descriptor_, &PB_QueryAMatch::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PB_QueryBFrame_0_descriptor_, &PB_QueryBFrame_0::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PB_QueryBMatch_descriptor_, &PB_QueryBMatch::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_proto_5fgen_2eproto() {
  delete PB_QueryAFrame_0::default_instance_;
  delete PB_QueryAFrame_0_reflection_;
  delete PB_QueryAMatch::default_instance_;
  delete PB_QueryAMatch_reflection_;
  delete PB_QueryBFrame_0::default_instance_;
  delete PB_QueryBFrame_0_reflection_;
  delete PB_QueryBMatch::default_instance_;
  delete PB_QueryBMatch_reflection_;
}

void protobuf_AddDesc_proto_5fgen_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_proto_5fgen_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017proto_gen.proto\"Z\n\020PB_QueryAFrame_0\022\n\n"
    "\002_0\030\001 \001(\005\022\n\n\002_1\030\002 \001(\t\022\n\n\002_2\030\003 \001(\005\022\n\n\002_3\030"
    "\004 \001(\005\022\n\n\002_4\030\005 \001(\005\022\n\n\002_5\030\006 \001(\005\"7\n\016PB_Quer"
    "yAMatch\022\n\n\002h1\030\001 \001(\005\022\n\n\002pw\030\002 \001(\t\022\r\n\005state"
    "\030\003 \001(\005\"*\n\020PB_QueryBFrame_0\022\n\n\002_0\030\001 \001(\005\022\n"
    "\n\002_1\030\002 \001(\005\"(\n\016PB_QueryBMatch\022\n\n\002a1\030\001 \001(\005"
    "\022\n\n\002h1\030\002 \001(\005b\006proto3", 260);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto_gen.proto", &protobuf_RegisterTypes);
  PB_QueryAFrame_0::default_instance_ = new PB_QueryAFrame_0();
  PB_QueryAMatch::default_instance_ = new PB_QueryAMatch();
  PB_QueryBFrame_0::default_instance_ = new PB_QueryBFrame_0();
  PB_QueryBMatch::default_instance_ = new PB_QueryBMatch();
  PB_QueryAFrame_0::default_instance_->InitAsDefaultInstance();
  PB_QueryAMatch::default_instance_->InitAsDefaultInstance();
  PB_QueryBFrame_0::default_instance_->InitAsDefaultInstance();
  PB_QueryBMatch::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_proto_5fgen_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_proto_5fgen_2eproto {
  StaticDescriptorInitializer_proto_5fgen_2eproto() {
    protobuf_AddDesc_proto_5fgen_2eproto();
  }
} static_descriptor_initializer_proto_5fgen_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PB_QueryAFrame_0::k0FieldNumber;
const int PB_QueryAFrame_0::k1FieldNumber;
const int PB_QueryAFrame_0::k2FieldNumber;
const int PB_QueryAFrame_0::k3FieldNumber;
const int PB_QueryAFrame_0::k4FieldNumber;
const int PB_QueryAFrame_0::k5FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PB_QueryAFrame_0::PB_QueryAFrame_0()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PB_QueryAFrame_0)
}

void PB_QueryAFrame_0::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PB_QueryAFrame_0::PB_QueryAFrame_0(const PB_QueryAFrame_0& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PB_QueryAFrame_0)
}

void PB_QueryAFrame_0::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _0_ = 0;
  _1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _2_ = 0;
  _3_ = 0;
  _4_ = 0;
  _5_ = 0;
}

PB_QueryAFrame_0::~PB_QueryAFrame_0() {
  // @@protoc_insertion_point(destructor:PB_QueryAFrame_0)
  SharedDtor();
}

void PB_QueryAFrame_0::SharedDtor() {
  _1_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void PB_QueryAFrame_0::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PB_QueryAFrame_0::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PB_QueryAFrame_0_descriptor_;
}

const PB_QueryAFrame_0& PB_QueryAFrame_0::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_5fgen_2eproto();
  return *default_instance_;
}

PB_QueryAFrame_0* PB_QueryAFrame_0::default_instance_ = NULL;

PB_QueryAFrame_0* PB_QueryAFrame_0::New(::google::protobuf::Arena* arena) const {
  PB_QueryAFrame_0* n = new PB_QueryAFrame_0;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PB_QueryAFrame_0::Clear() {
// @@protoc_insertion_point(message_clear_start:PB_QueryAFrame_0)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(PB_QueryAFrame_0, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PB_QueryAFrame_0*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(_0_, _5_);
  _1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool PB_QueryAFrame_0::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PB_QueryAFrame_0)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 _0 = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &_0_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse__1;
        break;
      }

      // optional string _1 = 2;
      case 2: {
        if (tag == 18) {
         parse__1:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable__1()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->_1().data(), this->_1().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PB_QueryAFrame_0._1"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse__2;
        break;
      }

      // optional int32 _2 = 3;
      case 3: {
        if (tag == 24) {
         parse__2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &_2_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse__3;
        break;
      }

      // optional int32 _3 = 4;
      case 4: {
        if (tag == 32) {
         parse__3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &_3_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse__4;
        break;
      }

      // optional int32 _4 = 5;
      case 5: {
        if (tag == 40) {
         parse__4:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &_4_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse__5;
        break;
      }

      // optional int32 _5 = 6;
      case 6: {
        if (tag == 48) {
         parse__5:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &_5_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PB_QueryAFrame_0)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PB_QueryAFrame_0)
  return false;
#undef DO_
}

void PB_QueryAFrame_0::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PB_QueryAFrame_0)
  // optional int32 _0 = 1;
  if (this->_0() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->_0(), output);
  }

  // optional string _1 = 2;
  if (this->_1().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_1().data(), this->_1().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB_QueryAFrame_0._1");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->_1(), output);
  }

  // optional int32 _2 = 3;
  if (this->_2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->_2(), output);
  }

  // optional int32 _3 = 4;
  if (this->_3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->_3(), output);
  }

  // optional int32 _4 = 5;
  if (this->_4() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->_4(), output);
  }

  // optional int32 _5 = 6;
  if (this->_5() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->_5(), output);
  }

  // @@protoc_insertion_point(serialize_end:PB_QueryAFrame_0)
}

::google::protobuf::uint8* PB_QueryAFrame_0::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB_QueryAFrame_0)
  // optional int32 _0 = 1;
  if (this->_0() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->_0(), target);
  }

  // optional string _1 = 2;
  if (this->_1().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->_1().data(), this->_1().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB_QueryAFrame_0._1");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->_1(), target);
  }

  // optional int32 _2 = 3;
  if (this->_2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->_2(), target);
  }

  // optional int32 _3 = 4;
  if (this->_3() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->_3(), target);
  }

  // optional int32 _4 = 5;
  if (this->_4() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->_4(), target);
  }

  // optional int32 _5 = 6;
  if (this->_5() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->_5(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:PB_QueryAFrame_0)
  return target;
}

int PB_QueryAFrame_0::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:PB_QueryAFrame_0)
  int total_size = 0;

  // optional int32 _0 = 1;
  if (this->_0() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->_0());
  }

  // optional string _1 = 2;
  if (this->_1().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->_1());
  }

  // optional int32 _2 = 3;
  if (this->_2() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->_2());
  }

  // optional int32 _3 = 4;
  if (this->_3() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->_3());
  }

  // optional int32 _4 = 5;
  if (this->_4() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->_4());
  }

  // optional int32 _5 = 6;
  if (this->_5() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->_5());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PB_QueryAFrame_0::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PB_QueryAFrame_0)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PB_QueryAFrame_0* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PB_QueryAFrame_0>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PB_QueryAFrame_0)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PB_QueryAFrame_0)
    MergeFrom(*source);
  }
}

void PB_QueryAFrame_0::MergeFrom(const PB_QueryAFrame_0& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PB_QueryAFrame_0)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._0() != 0) {
    set__0(from._0());
  }
  if (from._1().size() > 0) {

    _1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from._1_);
  }
  if (from._2() != 0) {
    set__2(from._2());
  }
  if (from._3() != 0) {
    set__3(from._3());
  }
  if (from._4() != 0) {
    set__4(from._4());
  }
  if (from._5() != 0) {
    set__5(from._5());
  }
}

void PB_QueryAFrame_0::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PB_QueryAFrame_0)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PB_QueryAFrame_0::CopyFrom(const PB_QueryAFrame_0& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB_QueryAFrame_0)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PB_QueryAFrame_0::IsInitialized() const {

  return true;
}

void PB_QueryAFrame_0::Swap(PB_QueryAFrame_0* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PB_QueryAFrame_0::InternalSwap(PB_QueryAFrame_0* other) {
  std::swap(_0_, other->_0_);
  _1_.Swap(&other->_1_);
  std::swap(_2_, other->_2_);
  std::swap(_3_, other->_3_);
  std::swap(_4_, other->_4_);
  std::swap(_5_, other->_5_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PB_QueryAFrame_0::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PB_QueryAFrame_0_descriptor_;
  metadata.reflection = PB_QueryAFrame_0_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PB_QueryAFrame_0

// optional int32 _0 = 1;
void PB_QueryAFrame_0::clear__0() {
  _0_ = 0;
}
 ::google::protobuf::int32 PB_QueryAFrame_0::_0() const {
  // @@protoc_insertion_point(field_get:PB_QueryAFrame_0._0)
  return _0_;
}
 void PB_QueryAFrame_0::set__0(::google::protobuf::int32 value) {
  
  _0_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryAFrame_0._0)
}

// optional string _1 = 2;
void PB_QueryAFrame_0::clear__1() {
  _1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& PB_QueryAFrame_0::_1() const {
  // @@protoc_insertion_point(field_get:PB_QueryAFrame_0._1)
  return _1_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PB_QueryAFrame_0::set__1(const ::std::string& value) {
  
  _1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PB_QueryAFrame_0._1)
}
 void PB_QueryAFrame_0::set__1(const char* value) {
  
  _1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PB_QueryAFrame_0._1)
}
 void PB_QueryAFrame_0::set__1(const char* value, size_t size) {
  
  _1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PB_QueryAFrame_0._1)
}
 ::std::string* PB_QueryAFrame_0::mutable__1() {
  
  // @@protoc_insertion_point(field_mutable:PB_QueryAFrame_0._1)
  return _1_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PB_QueryAFrame_0::release__1() {
  // @@protoc_insertion_point(field_release:PB_QueryAFrame_0._1)
  
  return _1_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PB_QueryAFrame_0::set_allocated__1(::std::string* _1) {
  if (_1 != NULL) {
    
  } else {
    
  }
  _1_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), _1);
  // @@protoc_insertion_point(field_set_allocated:PB_QueryAFrame_0._1)
}

// optional int32 _2 = 3;
void PB_QueryAFrame_0::clear__2() {
  _2_ = 0;
}
 ::google::protobuf::int32 PB_QueryAFrame_0::_2() const {
  // @@protoc_insertion_point(field_get:PB_QueryAFrame_0._2)
  return _2_;
}
 void PB_QueryAFrame_0::set__2(::google::protobuf::int32 value) {
  
  _2_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryAFrame_0._2)
}

// optional int32 _3 = 4;
void PB_QueryAFrame_0::clear__3() {
  _3_ = 0;
}
 ::google::protobuf::int32 PB_QueryAFrame_0::_3() const {
  // @@protoc_insertion_point(field_get:PB_QueryAFrame_0._3)
  return _3_;
}
 void PB_QueryAFrame_0::set__3(::google::protobuf::int32 value) {
  
  _3_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryAFrame_0._3)
}

// optional int32 _4 = 5;
void PB_QueryAFrame_0::clear__4() {
  _4_ = 0;
}
 ::google::protobuf::int32 PB_QueryAFrame_0::_4() const {
  // @@protoc_insertion_point(field_get:PB_QueryAFrame_0._4)
  return _4_;
}
 void PB_QueryAFrame_0::set__4(::google::protobuf::int32 value) {
  
  _4_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryAFrame_0._4)
}

// optional int32 _5 = 6;
void PB_QueryAFrame_0::clear__5() {
  _5_ = 0;
}
 ::google::protobuf::int32 PB_QueryAFrame_0::_5() const {
  // @@protoc_insertion_point(field_get:PB_QueryAFrame_0._5)
  return _5_;
}
 void PB_QueryAFrame_0::set__5(::google::protobuf::int32 value) {
  
  _5_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryAFrame_0._5)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PB_QueryAMatch::kH1FieldNumber;
const int PB_QueryAMatch::kPwFieldNumber;
const int PB_QueryAMatch::kStateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PB_QueryAMatch::PB_QueryAMatch()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PB_QueryAMatch)
}

void PB_QueryAMatch::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PB_QueryAMatch::PB_QueryAMatch(const PB_QueryAMatch& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PB_QueryAMatch)
}

void PB_QueryAMatch::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  h1_ = 0;
  pw_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  state_ = 0;
}

PB_QueryAMatch::~PB_QueryAMatch() {
  // @@protoc_insertion_point(destructor:PB_QueryAMatch)
  SharedDtor();
}

void PB_QueryAMatch::SharedDtor() {
  pw_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void PB_QueryAMatch::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PB_QueryAMatch::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PB_QueryAMatch_descriptor_;
}

const PB_QueryAMatch& PB_QueryAMatch::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_5fgen_2eproto();
  return *default_instance_;
}

PB_QueryAMatch* PB_QueryAMatch::default_instance_ = NULL;

PB_QueryAMatch* PB_QueryAMatch::New(::google::protobuf::Arena* arena) const {
  PB_QueryAMatch* n = new PB_QueryAMatch;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PB_QueryAMatch::Clear() {
// @@protoc_insertion_point(message_clear_start:PB_QueryAMatch)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(PB_QueryAMatch, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PB_QueryAMatch*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(h1_, state_);
  pw_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool PB_QueryAMatch::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PB_QueryAMatch)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 h1 = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &h1_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_pw;
        break;
      }

      // optional string pw = 2;
      case 2: {
        if (tag == 18) {
         parse_pw:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_pw()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->pw().data(), this->pw().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PB_QueryAMatch.pw"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_state;
        break;
      }

      // optional int32 state = 3;
      case 3: {
        if (tag == 24) {
         parse_state:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &state_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PB_QueryAMatch)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PB_QueryAMatch)
  return false;
#undef DO_
}

void PB_QueryAMatch::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PB_QueryAMatch)
  // optional int32 h1 = 1;
  if (this->h1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->h1(), output);
  }

  // optional string pw = 2;
  if (this->pw().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->pw().data(), this->pw().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB_QueryAMatch.pw");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->pw(), output);
  }

  // optional int32 state = 3;
  if (this->state() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->state(), output);
  }

  // @@protoc_insertion_point(serialize_end:PB_QueryAMatch)
}

::google::protobuf::uint8* PB_QueryAMatch::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB_QueryAMatch)
  // optional int32 h1 = 1;
  if (this->h1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->h1(), target);
  }

  // optional string pw = 2;
  if (this->pw().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->pw().data(), this->pw().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PB_QueryAMatch.pw");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->pw(), target);
  }

  // optional int32 state = 3;
  if (this->state() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->state(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:PB_QueryAMatch)
  return target;
}

int PB_QueryAMatch::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:PB_QueryAMatch)
  int total_size = 0;

  // optional int32 h1 = 1;
  if (this->h1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->h1());
  }

  // optional string pw = 2;
  if (this->pw().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->pw());
  }

  // optional int32 state = 3;
  if (this->state() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->state());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PB_QueryAMatch::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PB_QueryAMatch)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PB_QueryAMatch* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PB_QueryAMatch>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PB_QueryAMatch)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PB_QueryAMatch)
    MergeFrom(*source);
  }
}

void PB_QueryAMatch::MergeFrom(const PB_QueryAMatch& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PB_QueryAMatch)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.h1() != 0) {
    set_h1(from.h1());
  }
  if (from.pw().size() > 0) {

    pw_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pw_);
  }
  if (from.state() != 0) {
    set_state(from.state());
  }
}

void PB_QueryAMatch::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PB_QueryAMatch)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PB_QueryAMatch::CopyFrom(const PB_QueryAMatch& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB_QueryAMatch)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PB_QueryAMatch::IsInitialized() const {

  return true;
}

void PB_QueryAMatch::Swap(PB_QueryAMatch* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PB_QueryAMatch::InternalSwap(PB_QueryAMatch* other) {
  std::swap(h1_, other->h1_);
  pw_.Swap(&other->pw_);
  std::swap(state_, other->state_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PB_QueryAMatch::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PB_QueryAMatch_descriptor_;
  metadata.reflection = PB_QueryAMatch_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PB_QueryAMatch

// optional int32 h1 = 1;
void PB_QueryAMatch::clear_h1() {
  h1_ = 0;
}
 ::google::protobuf::int32 PB_QueryAMatch::h1() const {
  // @@protoc_insertion_point(field_get:PB_QueryAMatch.h1)
  return h1_;
}
 void PB_QueryAMatch::set_h1(::google::protobuf::int32 value) {
  
  h1_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryAMatch.h1)
}

// optional string pw = 2;
void PB_QueryAMatch::clear_pw() {
  pw_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& PB_QueryAMatch::pw() const {
  // @@protoc_insertion_point(field_get:PB_QueryAMatch.pw)
  return pw_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PB_QueryAMatch::set_pw(const ::std::string& value) {
  
  pw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PB_QueryAMatch.pw)
}
 void PB_QueryAMatch::set_pw(const char* value) {
  
  pw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PB_QueryAMatch.pw)
}
 void PB_QueryAMatch::set_pw(const char* value, size_t size) {
  
  pw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PB_QueryAMatch.pw)
}
 ::std::string* PB_QueryAMatch::mutable_pw() {
  
  // @@protoc_insertion_point(field_mutable:PB_QueryAMatch.pw)
  return pw_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PB_QueryAMatch::release_pw() {
  // @@protoc_insertion_point(field_release:PB_QueryAMatch.pw)
  
  return pw_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PB_QueryAMatch::set_allocated_pw(::std::string* pw) {
  if (pw != NULL) {
    
  } else {
    
  }
  pw_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pw);
  // @@protoc_insertion_point(field_set_allocated:PB_QueryAMatch.pw)
}

// optional int32 state = 3;
void PB_QueryAMatch::clear_state() {
  state_ = 0;
}
 ::google::protobuf::int32 PB_QueryAMatch::state() const {
  // @@protoc_insertion_point(field_get:PB_QueryAMatch.state)
  return state_;
}
 void PB_QueryAMatch::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryAMatch.state)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PB_QueryBFrame_0::k0FieldNumber;
const int PB_QueryBFrame_0::k1FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PB_QueryBFrame_0::PB_QueryBFrame_0()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PB_QueryBFrame_0)
}

void PB_QueryBFrame_0::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PB_QueryBFrame_0::PB_QueryBFrame_0(const PB_QueryBFrame_0& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PB_QueryBFrame_0)
}

void PB_QueryBFrame_0::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  _0_ = 0;
  _1_ = 0;
}

PB_QueryBFrame_0::~PB_QueryBFrame_0() {
  // @@protoc_insertion_point(destructor:PB_QueryBFrame_0)
  SharedDtor();
}

void PB_QueryBFrame_0::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PB_QueryBFrame_0::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PB_QueryBFrame_0::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PB_QueryBFrame_0_descriptor_;
}

const PB_QueryBFrame_0& PB_QueryBFrame_0::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_5fgen_2eproto();
  return *default_instance_;
}

PB_QueryBFrame_0* PB_QueryBFrame_0::default_instance_ = NULL;

PB_QueryBFrame_0* PB_QueryBFrame_0::New(::google::protobuf::Arena* arena) const {
  PB_QueryBFrame_0* n = new PB_QueryBFrame_0;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PB_QueryBFrame_0::Clear() {
// @@protoc_insertion_point(message_clear_start:PB_QueryBFrame_0)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(PB_QueryBFrame_0, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PB_QueryBFrame_0*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(_0_, _1_);

#undef ZR_HELPER_
#undef ZR_

}

bool PB_QueryBFrame_0::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PB_QueryBFrame_0)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 _0 = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &_0_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse__1;
        break;
      }

      // optional int32 _1 = 2;
      case 2: {
        if (tag == 16) {
         parse__1:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &_1_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PB_QueryBFrame_0)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PB_QueryBFrame_0)
  return false;
#undef DO_
}

void PB_QueryBFrame_0::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PB_QueryBFrame_0)
  // optional int32 _0 = 1;
  if (this->_0() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->_0(), output);
  }

  // optional int32 _1 = 2;
  if (this->_1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->_1(), output);
  }

  // @@protoc_insertion_point(serialize_end:PB_QueryBFrame_0)
}

::google::protobuf::uint8* PB_QueryBFrame_0::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB_QueryBFrame_0)
  // optional int32 _0 = 1;
  if (this->_0() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->_0(), target);
  }

  // optional int32 _1 = 2;
  if (this->_1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->_1(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:PB_QueryBFrame_0)
  return target;
}

int PB_QueryBFrame_0::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:PB_QueryBFrame_0)
  int total_size = 0;

  // optional int32 _0 = 1;
  if (this->_0() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->_0());
  }

  // optional int32 _1 = 2;
  if (this->_1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->_1());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PB_QueryBFrame_0::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PB_QueryBFrame_0)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PB_QueryBFrame_0* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PB_QueryBFrame_0>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PB_QueryBFrame_0)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PB_QueryBFrame_0)
    MergeFrom(*source);
  }
}

void PB_QueryBFrame_0::MergeFrom(const PB_QueryBFrame_0& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PB_QueryBFrame_0)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._0() != 0) {
    set__0(from._0());
  }
  if (from._1() != 0) {
    set__1(from._1());
  }
}

void PB_QueryBFrame_0::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PB_QueryBFrame_0)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PB_QueryBFrame_0::CopyFrom(const PB_QueryBFrame_0& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB_QueryBFrame_0)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PB_QueryBFrame_0::IsInitialized() const {

  return true;
}

void PB_QueryBFrame_0::Swap(PB_QueryBFrame_0* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PB_QueryBFrame_0::InternalSwap(PB_QueryBFrame_0* other) {
  std::swap(_0_, other->_0_);
  std::swap(_1_, other->_1_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PB_QueryBFrame_0::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PB_QueryBFrame_0_descriptor_;
  metadata.reflection = PB_QueryBFrame_0_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PB_QueryBFrame_0

// optional int32 _0 = 1;
void PB_QueryBFrame_0::clear__0() {
  _0_ = 0;
}
 ::google::protobuf::int32 PB_QueryBFrame_0::_0() const {
  // @@protoc_insertion_point(field_get:PB_QueryBFrame_0._0)
  return _0_;
}
 void PB_QueryBFrame_0::set__0(::google::protobuf::int32 value) {
  
  _0_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryBFrame_0._0)
}

// optional int32 _1 = 2;
void PB_QueryBFrame_0::clear__1() {
  _1_ = 0;
}
 ::google::protobuf::int32 PB_QueryBFrame_0::_1() const {
  // @@protoc_insertion_point(field_get:PB_QueryBFrame_0._1)
  return _1_;
}
 void PB_QueryBFrame_0::set__1(::google::protobuf::int32 value) {
  
  _1_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryBFrame_0._1)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PB_QueryBMatch::kA1FieldNumber;
const int PB_QueryBMatch::kH1FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PB_QueryBMatch::PB_QueryBMatch()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PB_QueryBMatch)
}

void PB_QueryBMatch::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PB_QueryBMatch::PB_QueryBMatch(const PB_QueryBMatch& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PB_QueryBMatch)
}

void PB_QueryBMatch::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  a1_ = 0;
  h1_ = 0;
}

PB_QueryBMatch::~PB_QueryBMatch() {
  // @@protoc_insertion_point(destructor:PB_QueryBMatch)
  SharedDtor();
}

void PB_QueryBMatch::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PB_QueryBMatch::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PB_QueryBMatch::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PB_QueryBMatch_descriptor_;
}

const PB_QueryBMatch& PB_QueryBMatch::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_5fgen_2eproto();
  return *default_instance_;
}

PB_QueryBMatch* PB_QueryBMatch::default_instance_ = NULL;

PB_QueryBMatch* PB_QueryBMatch::New(::google::protobuf::Arena* arena) const {
  PB_QueryBMatch* n = new PB_QueryBMatch;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PB_QueryBMatch::Clear() {
// @@protoc_insertion_point(message_clear_start:PB_QueryBMatch)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(PB_QueryBMatch, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PB_QueryBMatch*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(a1_, h1_);

#undef ZR_HELPER_
#undef ZR_

}

bool PB_QueryBMatch::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PB_QueryBMatch)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 a1 = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &a1_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_h1;
        break;
      }

      // optional int32 h1 = 2;
      case 2: {
        if (tag == 16) {
         parse_h1:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &h1_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PB_QueryBMatch)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PB_QueryBMatch)
  return false;
#undef DO_
}

void PB_QueryBMatch::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PB_QueryBMatch)
  // optional int32 a1 = 1;
  if (this->a1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->a1(), output);
  }

  // optional int32 h1 = 2;
  if (this->h1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->h1(), output);
  }

  // @@protoc_insertion_point(serialize_end:PB_QueryBMatch)
}

::google::protobuf::uint8* PB_QueryBMatch::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB_QueryBMatch)
  // optional int32 a1 = 1;
  if (this->a1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->a1(), target);
  }

  // optional int32 h1 = 2;
  if (this->h1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->h1(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:PB_QueryBMatch)
  return target;
}

int PB_QueryBMatch::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:PB_QueryBMatch)
  int total_size = 0;

  // optional int32 a1 = 1;
  if (this->a1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->a1());
  }

  // optional int32 h1 = 2;
  if (this->h1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->h1());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PB_QueryBMatch::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PB_QueryBMatch)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PB_QueryBMatch* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PB_QueryBMatch>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PB_QueryBMatch)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PB_QueryBMatch)
    MergeFrom(*source);
  }
}

void PB_QueryBMatch::MergeFrom(const PB_QueryBMatch& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PB_QueryBMatch)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.a1() != 0) {
    set_a1(from.a1());
  }
  if (from.h1() != 0) {
    set_h1(from.h1());
  }
}

void PB_QueryBMatch::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PB_QueryBMatch)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PB_QueryBMatch::CopyFrom(const PB_QueryBMatch& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB_QueryBMatch)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PB_QueryBMatch::IsInitialized() const {

  return true;
}

void PB_QueryBMatch::Swap(PB_QueryBMatch* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PB_QueryBMatch::InternalSwap(PB_QueryBMatch* other) {
  std::swap(a1_, other->a1_);
  std::swap(h1_, other->h1_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PB_QueryBMatch::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PB_QueryBMatch_descriptor_;
  metadata.reflection = PB_QueryBMatch_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PB_QueryBMatch

// optional int32 a1 = 1;
void PB_QueryBMatch::clear_a1() {
  a1_ = 0;
}
 ::google::protobuf::int32 PB_QueryBMatch::a1() const {
  // @@protoc_insertion_point(field_get:PB_QueryBMatch.a1)
  return a1_;
}
 void PB_QueryBMatch::set_a1(::google::protobuf::int32 value) {
  
  a1_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryBMatch.a1)
}

// optional int32 h1 = 2;
void PB_QueryBMatch::clear_h1() {
  h1_ = 0;
}
 ::google::protobuf::int32 PB_QueryBMatch::h1() const {
  // @@protoc_insertion_point(field_get:PB_QueryBMatch.h1)
  return h1_;
}
 void PB_QueryBMatch::set_h1(::google::protobuf::int32 value) {
  
  h1_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryBMatch.h1)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
