// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_gen.proto

#ifndef PROTOBUF_proto_5fgen_2eproto__INCLUDED
#define PROTOBUF_proto_5fgen_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_proto_5fgen_2eproto();
void protobuf_AssignDesc_proto_5fgen_2eproto();
void protobuf_ShutdownFile_proto_5fgen_2eproto();

class PB_QueryAFrame_0;
class PB_QueryAMatch;
class PB_QueryBFrame_0;
class PB_QueryBMatch;

// ===================================================================

class PB_QueryAFrame_0 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PB_QueryAFrame_0) */ {
 public:
  PB_QueryAFrame_0();
  virtual ~PB_QueryAFrame_0();

  PB_QueryAFrame_0(const PB_QueryAFrame_0& from);

  inline PB_QueryAFrame_0& operator=(const PB_QueryAFrame_0& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_QueryAFrame_0& default_instance();

  void Swap(PB_QueryAFrame_0* other);

  // implements Message ----------------------------------------------

  inline PB_QueryAFrame_0* New() const { return New(NULL); }

  PB_QueryAFrame_0* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_QueryAFrame_0& from);
  void MergeFrom(const PB_QueryAFrame_0& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PB_QueryAFrame_0* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 _0 = 1;
  void clear__0();
  static const int k0FieldNumber = 1;
  ::google::protobuf::int32 _0() const;
  void set__0(::google::protobuf::int32 value);

  // optional int32 _1 = 2;
  void clear__1();
  static const int k1FieldNumber = 2;
  ::google::protobuf::int32 _1() const;
  void set__1(::google::protobuf::int32 value);

  // optional int32 _2 = 3;
  void clear__2();
  static const int k2FieldNumber = 3;
  ::google::protobuf::int32 _2() const;
  void set__2(::google::protobuf::int32 value);

  // optional int32 _3 = 4;
  void clear__3();
  static const int k3FieldNumber = 4;
  ::google::protobuf::int32 _3() const;
  void set__3(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PB_QueryAFrame_0)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 _0_;
  ::google::protobuf::int32 _1_;
  ::google::protobuf::int32 _2_;
  ::google::protobuf::int32 _3_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_5fgen_2eproto();
  friend void protobuf_AssignDesc_proto_5fgen_2eproto();
  friend void protobuf_ShutdownFile_proto_5fgen_2eproto();

  void InitAsDefaultInstance();
  static PB_QueryAFrame_0* default_instance_;
};
// -------------------------------------------------------------------

class PB_QueryAMatch : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PB_QueryAMatch) */ {
 public:
  PB_QueryAMatch();
  virtual ~PB_QueryAMatch();

  PB_QueryAMatch(const PB_QueryAMatch& from);

  inline PB_QueryAMatch& operator=(const PB_QueryAMatch& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_QueryAMatch& default_instance();

  void Swap(PB_QueryAMatch* other);

  // implements Message ----------------------------------------------

  inline PB_QueryAMatch* New() const { return New(NULL); }

  PB_QueryAMatch* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_QueryAMatch& from);
  void MergeFrom(const PB_QueryAMatch& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PB_QueryAMatch* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 h1 = 1;
  void clear_h1();
  static const int kH1FieldNumber = 1;
  ::google::protobuf::int32 h1() const;
  void set_h1(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PB_QueryAMatch)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 h1_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_5fgen_2eproto();
  friend void protobuf_AssignDesc_proto_5fgen_2eproto();
  friend void protobuf_ShutdownFile_proto_5fgen_2eproto();

  void InitAsDefaultInstance();
  static PB_QueryAMatch* default_instance_;
};
// -------------------------------------------------------------------

class PB_QueryBFrame_0 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PB_QueryBFrame_0) */ {
 public:
  PB_QueryBFrame_0();
  virtual ~PB_QueryBFrame_0();

  PB_QueryBFrame_0(const PB_QueryBFrame_0& from);

  inline PB_QueryBFrame_0& operator=(const PB_QueryBFrame_0& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_QueryBFrame_0& default_instance();

  void Swap(PB_QueryBFrame_0* other);

  // implements Message ----------------------------------------------

  inline PB_QueryBFrame_0* New() const { return New(NULL); }

  PB_QueryBFrame_0* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_QueryBFrame_0& from);
  void MergeFrom(const PB_QueryBFrame_0& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PB_QueryBFrame_0* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 _0 = 1;
  void clear__0();
  static const int k0FieldNumber = 1;
  ::google::protobuf::int32 _0() const;
  void set__0(::google::protobuf::int32 value);

  // optional int32 _1 = 2;
  void clear__1();
  static const int k1FieldNumber = 2;
  ::google::protobuf::int32 _1() const;
  void set__1(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PB_QueryBFrame_0)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 _0_;
  ::google::protobuf::int32 _1_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_5fgen_2eproto();
  friend void protobuf_AssignDesc_proto_5fgen_2eproto();
  friend void protobuf_ShutdownFile_proto_5fgen_2eproto();

  void InitAsDefaultInstance();
  static PB_QueryBFrame_0* default_instance_;
};
// -------------------------------------------------------------------

class PB_QueryBMatch : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PB_QueryBMatch) */ {
 public:
  PB_QueryBMatch();
  virtual ~PB_QueryBMatch();

  PB_QueryBMatch(const PB_QueryBMatch& from);

  inline PB_QueryBMatch& operator=(const PB_QueryBMatch& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_QueryBMatch& default_instance();

  void Swap(PB_QueryBMatch* other);

  // implements Message ----------------------------------------------

  inline PB_QueryBMatch* New() const { return New(NULL); }

  PB_QueryBMatch* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_QueryBMatch& from);
  void MergeFrom(const PB_QueryBMatch& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PB_QueryBMatch* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 a1 = 1;
  void clear_a1();
  static const int kA1FieldNumber = 1;
  ::google::protobuf::int32 a1() const;
  void set_a1(::google::protobuf::int32 value);

  // optional int32 h1 = 2;
  void clear_h1();
  static const int kH1FieldNumber = 2;
  ::google::protobuf::int32 h1() const;
  void set_h1(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PB_QueryBMatch)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 a1_;
  ::google::protobuf::int32 h1_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_5fgen_2eproto();
  friend void protobuf_AssignDesc_proto_5fgen_2eproto();
  friend void protobuf_ShutdownFile_proto_5fgen_2eproto();

  void InitAsDefaultInstance();
  static PB_QueryBMatch* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PB_QueryAFrame_0

// optional int32 _0 = 1;
inline void PB_QueryAFrame_0::clear__0() {
  _0_ = 0;
}
inline ::google::protobuf::int32 PB_QueryAFrame_0::_0() const {
  // @@protoc_insertion_point(field_get:PB_QueryAFrame_0._0)
  return _0_;
}
inline void PB_QueryAFrame_0::set__0(::google::protobuf::int32 value) {
  
  _0_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryAFrame_0._0)
}

// optional int32 _1 = 2;
inline void PB_QueryAFrame_0::clear__1() {
  _1_ = 0;
}
inline ::google::protobuf::int32 PB_QueryAFrame_0::_1() const {
  // @@protoc_insertion_point(field_get:PB_QueryAFrame_0._1)
  return _1_;
}
inline void PB_QueryAFrame_0::set__1(::google::protobuf::int32 value) {
  
  _1_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryAFrame_0._1)
}

// optional int32 _2 = 3;
inline void PB_QueryAFrame_0::clear__2() {
  _2_ = 0;
}
inline ::google::protobuf::int32 PB_QueryAFrame_0::_2() const {
  // @@protoc_insertion_point(field_get:PB_QueryAFrame_0._2)
  return _2_;
}
inline void PB_QueryAFrame_0::set__2(::google::protobuf::int32 value) {
  
  _2_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryAFrame_0._2)
}

// optional int32 _3 = 4;
inline void PB_QueryAFrame_0::clear__3() {
  _3_ = 0;
}
inline ::google::protobuf::int32 PB_QueryAFrame_0::_3() const {
  // @@protoc_insertion_point(field_get:PB_QueryAFrame_0._3)
  return _3_;
}
inline void PB_QueryAFrame_0::set__3(::google::protobuf::int32 value) {
  
  _3_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryAFrame_0._3)
}

// -------------------------------------------------------------------

// PB_QueryAMatch

// optional int32 h1 = 1;
inline void PB_QueryAMatch::clear_h1() {
  h1_ = 0;
}
inline ::google::protobuf::int32 PB_QueryAMatch::h1() const {
  // @@protoc_insertion_point(field_get:PB_QueryAMatch.h1)
  return h1_;
}
inline void PB_QueryAMatch::set_h1(::google::protobuf::int32 value) {
  
  h1_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryAMatch.h1)
}

// -------------------------------------------------------------------

// PB_QueryBFrame_0

// optional int32 _0 = 1;
inline void PB_QueryBFrame_0::clear__0() {
  _0_ = 0;
}
inline ::google::protobuf::int32 PB_QueryBFrame_0::_0() const {
  // @@protoc_insertion_point(field_get:PB_QueryBFrame_0._0)
  return _0_;
}
inline void PB_QueryBFrame_0::set__0(::google::protobuf::int32 value) {
  
  _0_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryBFrame_0._0)
}

// optional int32 _1 = 2;
inline void PB_QueryBFrame_0::clear__1() {
  _1_ = 0;
}
inline ::google::protobuf::int32 PB_QueryBFrame_0::_1() const {
  // @@protoc_insertion_point(field_get:PB_QueryBFrame_0._1)
  return _1_;
}
inline void PB_QueryBFrame_0::set__1(::google::protobuf::int32 value) {
  
  _1_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryBFrame_0._1)
}

// -------------------------------------------------------------------

// PB_QueryBMatch

// optional int32 a1 = 1;
inline void PB_QueryBMatch::clear_a1() {
  a1_ = 0;
}
inline ::google::protobuf::int32 PB_QueryBMatch::a1() const {
  // @@protoc_insertion_point(field_get:PB_QueryBMatch.a1)
  return a1_;
}
inline void PB_QueryBMatch::set_a1(::google::protobuf::int32 value) {
  
  a1_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryBMatch.a1)
}

// optional int32 h1 = 2;
inline void PB_QueryBMatch::clear_h1() {
  h1_ = 0;
}
inline ::google::protobuf::int32 PB_QueryBMatch::h1() const {
  // @@protoc_insertion_point(field_get:PB_QueryBMatch.h1)
  return h1_;
}
inline void PB_QueryBMatch::set_h1(::google::protobuf::int32 value) {
  
  h1_ = value;
  // @@protoc_insertion_point(field_set:PB_QueryBMatch.h1)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_5fgen_2eproto__INCLUDED
