<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PlatformModel" nsURI="http://cpp/tool/platform" nsPrefix="hu.bme.mit.localsearch.cpp.tool.derivedapi">
  <eClassifiers xsi:type="ecore:EClass" name="Camera">
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibleFor" upperBound="-1"
        eType="ecore:EClass model.ecore#//Segment"/>
  </eClassifiers>
</ecore:EPackage>
