.PHONY: clean All

All:
	@echo "----------Building project:[ Tank - Debug ]----------"
	@cd "Tank" && "$(MAKE)" -f  "Tank.mk"
clean:
	@echo "----------Cleaning project:[ Tank - Debug ]----------"
	@cd "Tank" && "$(MAKE)" -f  "Tank.mk" clean
