<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="factory" nsURI="http://factory.ecore/tanks" nsPrefix="tanks">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="settingDelegates" value="org.eclipse.viatra.query.querybasedfeature"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Tartaly">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tarol" eType="#//Anyag"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allapot" eType="#//Halmazallapot"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="org.eclipse.viatra.query.querybasedfeature">
        <details key="patternFQN" value="tanks.queries.szilard"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anyag"/>
  <eClassifiers xsi:type="ecore:EClass" name="Viz" eSuperTypes="#//Anyag"/>
  <eClassifiers xsi:type="ecore:EClass" name="Halmazallapot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Folyekony" eSuperTypes="#//Halmazallapot"/>
  <eClassifiers xsi:type="ecore:EClass" name="Goz" eSuperTypes="#//Halmazallapot"/>
  <eClassifiers xsi:type="ecore:EClass" name="Szilard" eSuperTypes="#//Halmazallapot"/>
</ecore:EPackage>
